version: '3'

services:
  server:
    image: server-image
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port to host

  client:
    image: client-image
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map container port to host
